// Lightweight location data - replaces 35MB countries-states-cities package
export interface Country {
  cca2: string;
  name: string;
  callingCode: string[];
  flag: string;
}

export interface State {
  name: string;
  cities?: string[];
}

export const COUNTRIES: Country[] = [
  // African Countries
  { cca2: 'NG', name: 'Nigeria', callingCode: ['234'], flag: '🇳🇬' },
  { cca2: 'ZA', name: 'South Africa', callingCode: ['27'], flag: '🇿🇦' },
  { cca2: 'EG', name: 'Egypt', callingCode: ['20'], flag: '🇪🇬' },
  { cca2: 'KE', name: 'Kenya', callingCode: ['254'], flag: '🇰🇪' },
  { cca2: 'GH', name: 'Ghana', callingCode: ['233'], flag: '🇬🇭' },
  { cca2: 'ET', name: 'Ethiopia', callingCode: ['251'], flag: '��' },
  { cca2: 'UG', name: 'Uganda', callingCode: ['256'], flag: '🇺🇬' },
  { cca2: 'TZ', name: 'Tanzania', callingCode: ['255'], flag: '🇹🇿' },
  { cca2: 'DZ', name: 'Algeria', callingCode: ['213'], flag: '🇩🇿' },
  { cca2: 'MA', name: 'Morocco', callingCode: ['212'], flag: '🇲🇦' },
  { cca2: 'AO', name: 'Angola', callingCode: ['244'], flag: '🇦🇴' },
  { cca2: 'MZ', name: 'Mozambique', callingCode: ['258'], flag: '��' },
  { cca2: 'MG', name: 'Madagascar', callingCode: ['261'], flag: '🇲🇬' },
  { cca2: 'CM', name: 'Cameroon', callingCode: ['237'], flag: '🇨🇲' },
  { cca2: 'CI', name: 'Côte d\'Ivoire', callingCode: ['225'], flag: '��' },
  { cca2: 'NE', name: 'Niger', callingCode: ['227'], flag: '🇳🇪' },
  { cca2: 'BF', name: 'Burkina Faso', callingCode: ['226'], flag: '🇧🇫' },
  { cca2: 'ML', name: 'Mali', callingCode: ['223'], flag: '🇲🇱' },
  { cca2: 'MW', name: 'Malawi', callingCode: ['265'], flag: '��' },
  { cca2: 'ZM', name: 'Zambia', callingCode: ['260'], flag: '🇿🇲' },
  { cca2: 'SN', name: 'Senegal', callingCode: ['221'], flag: '��' },
  { cca2: 'SO', name: 'Somalia', callingCode: ['252'], flag: '🇸🇴' },
  { cca2: 'TD', name: 'Chad', callingCode: ['235'], flag: '🇹🇩' },
  { cca2: 'GN', name: 'Guinea', callingCode: ['224'], flag: '�🇳' },
  { cca2: 'RW', name: 'Rwanda', callingCode: ['250'], flag: '🇷🇼' },
  { cca2: 'BJ', name: 'Benin', callingCode: ['229'], flag: '🇧🇯' },
  { cca2: 'TN', name: 'Tunisia', callingCode: ['216'], flag: '�🇳' },
  { cca2: 'BI', name: 'Burundi', callingCode: ['257'], flag: '🇧🇮' },
  { cca2: 'TG', name: 'Togo', callingCode: ['228'], flag: '🇹🇬' },
  { cca2: 'SL', name: 'Sierra Leone', callingCode: ['232'], flag: '🇸🇱' },
  { cca2: 'LY', name: 'Libya', callingCode: ['218'], flag: '🇱🇾' },
  { cca2: 'LR', name: 'Liberia', callingCode: ['231'], flag: '��' },
  { cca2: 'CF', name: 'Central African Republic', callingCode: ['236'], flag: '��' },
  { cca2: 'MR', name: 'Mauritania', callingCode: ['222'], flag: '�🇷' },
  { cca2: 'ER', name: 'Eritrea', callingCode: ['291'], flag: '🇪🇷' },
  { cca2: 'GM', name: 'Gambia', callingCode: ['220'], flag: '🇬🇲' },
  { cca2: 'BW', name: 'Botswana', callingCode: ['267'], flag: '��' },
  { cca2: 'NA', name: 'Namibia', callingCode: ['264'], flag: '🇳🇦' },
  { cca2: 'GA', name: 'Gabon', callingCode: ['241'], flag: '🇬🇦' },
  { cca2: 'LS', name: 'Lesotho', callingCode: ['266'], flag: '🇱🇸' },
  { cca2: 'GW', name: 'Guinea-Bissau', callingCode: ['245'], flag: '��' },
  { cca2: 'GQ', name: 'Equatorial Guinea', callingCode: ['240'], flag: '🇬🇶' },
  { cca2: 'MU', name: 'Mauritius', callingCode: ['230'], flag: '��' },
  { cca2: 'SZ', name: 'Eswatini', callingCode: ['268'], flag: '🇸🇿' },
  { cca2: 'DJ', name: 'Djibouti', callingCode: ['253'], flag: '🇩🇯' },
  { cca2: 'KM', name: 'Comoros', callingCode: ['269'], flag: '🇰🇲' },
  { cca2: 'CV', name: 'Cape Verde', callingCode: ['238'], flag: '🇨🇻' },
  { cca2: 'ST', name: 'São Tomé and Príncipe', callingCode: ['239'], flag: '🇸🇹' },
  { cca2: 'SC', name: 'Seychelles', callingCode: ['248'], flag: '🇸🇨' },

  // Other Countries
  { cca2: 'US', name: 'United States', callingCode: ['1'], flag: '🇺🇸' },
  { cca2: 'GB', name: 'United Kingdom', callingCode: ['44'], flag: '🇬🇧' },
  { cca2: 'FR', name: 'France', callingCode: ['33'], flag: '🇫🇷' },
  { cca2: 'DE', name: 'Germany', callingCode: ['49'], flag: '�🇪' },
  { cca2: 'JP', name: 'Japan', callingCode: ['81'], flag: '🇯🇵' },
  { cca2: 'CN', name: 'China', callingCode: ['86'], flag: '🇨🇳' },
  { cca2: 'IN', name: 'India', callingCode: ['91'], flag: '🇮🇳' },
  { cca2: 'CA', name: 'Canada', callingCode: ['1'], flag: '🇨🇦' },
  { cca2: 'AU', name: 'Australia', callingCode: ['61'], flag: '🇦🇺' },
  { cca2: 'BR', name: 'Brazil', callingCode: ['55'], flag: '🇧🇷' },
  { cca2: 'MX', name: 'Mexico', callingCode: ['52'], flag: '��' },
];

export const STATES_BY_COUNTRY: Record<string, State[]> = {
  NG: [
    { name: 'Abia', cities: ['Umuahia', 'Aba', 'Arochukwu', 'Ohafia'] },
    { name: 'Adamawa', cities: ['Yola', 'Mubi', 'Numan', 'Jimeta'] },
    { name: 'Akwa Ibom', cities: ['Uyo', 'Ikot Ekpene', 'Eket', 'Oron'] },
    { name: 'Anambra', cities: ['Awka', 'Onitsha', 'Nnewi', 'Ekwulobia'] },
    { name: 'Bauchi', cities: ['Bauchi', 'Azare', 'Misau', 'Jama\'are'] },
    { name: 'Bayelsa', cities: ['Yenagoa', 'Brass', 'Sagbama', 'Ogbia'] },
    { name: 'Benue', cities: ['Makurdi', 'Gboko', 'Otukpo', 'Katsina-Ala'] },
    { name: 'Borno', cities: ['Maiduguri', 'Biu', 'Bama', 'Dikwa'] },
    { name: 'Cross River', cities: ['Calabar', 'Ugep', 'Ogoja', 'Ikom'] },
    { name: 'Delta', cities: ['Asaba', 'Warri', 'Sapele', 'Ughelli'] },
    { name: 'Ebonyi', cities: ['Abakaliki', 'Afikpo', 'Onueke', 'Ezza'] },
    { name: 'Edo', cities: ['Benin City', 'Auchi', 'Ekpoma', 'Uromi'] },
    { name: 'Ekiti', cities: ['Ado-Ekiti', 'Ikere', 'Oye', 'Ijero'] },
    { name: 'Enugu', cities: ['Enugu', 'Nsukka', 'Oji River', 'Awgu'] },
    { name: 'FCT', cities: ['Abuja', 'Gwagwalada', 'Kuje', 'Bwari'] },
    { name: 'Gombe', cities: ['Gombe', 'Billiri', 'Kaltungo', 'Dukku'] },
    { name: 'Imo', cities: ['Owerri', 'Orlu', 'Okigwe', 'Mbaise'] },
    { name: 'Jigawa', cities: ['Dutse', 'Hadejia', 'Kazaure', 'Ringim'] },
    { name: 'Kaduna', cities: ['Kaduna', 'Zaria', 'Kafanchan', 'Sabon Gari'] },
    { name: 'Kano', cities: ['Kano', 'Wudil', 'Gwarzo', 'Rano'] },
    { name: 'Katsina', cities: ['Katsina', 'Daura', 'Funtua', 'Malumfashi'] },
    { name: 'Kebbi', cities: ['Birnin Kebbi', 'Argungu', 'Yauri', 'Zuru'] },
    { name: 'Kogi', cities: ['Lokoja', 'Okene', 'Kabba', 'Anyigba'] },
    { name: 'Kwara', cities: ['Ilorin', 'Offa', 'Omu-Aran', 'Lafiagi'] },
    { name: 'Lagos', cities: ['Lagos', 'Ikeja', 'Epe', 'Badagry', 'Ikorodu'] },
    { name: 'Nasarawa', cities: ['Lafia', 'Keffi', 'Akwanga', 'Nasarawa'] },
    { name: 'Niger', cities: ['Minna', 'Bida', 'Kontagora', 'Suleja'] },
    { name: 'Ogun', cities: ['Abeokuta', 'Sagamu', 'Ijebu-Ode', 'Ilaro'] },
    { name: 'Ondo', cities: ['Akure', 'Ondo', 'Owo', 'Ikare'] },
    { name: 'Osun', cities: ['Osogbo', 'Ile-Ife', 'Ilesa', 'Ede'] },
    { name: 'Oyo', cities: ['Ibadan', 'Ogbomoso', 'Oyo', 'Iseyin'] },
    { name: 'Plateau', cities: ['Jos', 'Bukuru', 'Shendam', 'Pankshin'] },
    { name: 'Rivers', cities: ['Port Harcourt', 'Obio-Akpor', 'Okrika', 'Bonny'] },
    { name: 'Sokoto', cities: ['Sokoto', 'Tambuwal', 'Gwadabawa', 'Bodinga'] },
    { name: 'Taraba', cities: ['Jalingo', 'Wukari', 'Bali', 'Gembu'] },
    { name: 'Yobe', cities: ['Damaturu', 'Potiskum', 'Gashua', 'Nguru'] },
    { name: 'Zamfara', cities: ['Gusau', 'Kaura Namoda', 'Talata Mafara', 'Anka'] },
  ],
  US: [
    { name: 'Alabama' }, { name: 'Alaska' }, { name: 'Arizona' }, { name: 'Arkansas' },
    { name: 'California' }, { name: 'Colorado' }, { name: 'Connecticut' }, { name: 'Delaware' },
    { name: 'Florida' }, { name: 'Georgia' }, { name: 'Hawaii' }, { name: 'Idaho' },
    { name: 'Illinois' }, { name: 'Indiana' }, { name: 'Iowa' }, { name: 'Kansas' },
    { name: 'Kentucky' }, { name: 'Louisiana' }, { name: 'Maine' }, { name: 'Maryland' },
    { name: 'Massachusetts' }, { name: 'Michigan' }, { name: 'Minnesota' }, { name: 'Mississippi' },
    { name: 'Missouri' }, { name: 'Montana' }, { name: 'Nebraska' }, { name: 'Nevada' },
    { name: 'New Hampshire' }, { name: 'New Jersey' }, { name: 'New Mexico' }, { name: 'New York' },
    { name: 'North Carolina' }, { name: 'North Dakota' }, { name: 'Ohio' }, { name: 'Oklahoma' },
    { name: 'Oregon' }, { name: 'Pennsylvania' }, { name: 'Rhode Island' }, { name: 'South Carolina' },
    { name: 'South Dakota' }, { name: 'Tennessee' }, { name: 'Texas' }, { name: 'Utah' },
    { name: 'Vermont' }, { name: 'Virginia' }, { name: 'Washington' }, { name: 'West Virginia' },
    { name: 'Wisconsin' }, { name: 'Wyoming' }
  ],
  GB: [
    { name: 'England' }, { name: 'Scotland' }, { name: 'Wales' }, { name: 'Northern Ireland' }
  ],
  ZA: [
    { name: 'Eastern Cape', cities: ['Port Elizabeth', 'East London', 'Grahamstown', 'King William\'s Town'] },
    { name: 'Free State', cities: ['Bloemfontein', 'Welkom', 'Kroonstad', 'Bethlehem'] },
    { name: 'Gauteng', cities: ['Johannesburg', 'Pretoria', 'Soweto', 'Sandton'] },
    { name: 'KwaZulu-Natal', cities: ['Durban', 'Pietermaritzburg', 'Newcastle', 'Richards Bay'] },
    { name: 'Limpopo', cities: ['Polokwane', 'Tzaneen', 'Thohoyandou', 'Giyani'] },
    { name: 'Mpumalanga', cities: ['Nelspruit', 'Witbank', 'Secunda', 'Standerton'] },
    { name: 'Northern Cape', cities: ['Kimberley', 'Upington', 'Springbok', 'De Aar'] },
    { name: 'North West', cities: ['Mahikeng', 'Rustenburg', 'Klerksdorp', 'Potchefstroom'] },
    { name: 'Western Cape', cities: ['Cape Town', 'Stellenbosch', 'Paarl', 'George'] },
  ],
  EG: [
    { name: 'Cairo', cities: ['Cairo', 'Giza', 'Shubra El Kheima', 'Helwan'] },
    { name: 'Alexandria', cities: ['Alexandria', 'Borg El Arab', 'Abu Qir'] },
    { name: 'Giza', cities: ['Giza', '6th of October City', 'Sheikh Zayed City'] },
    { name: 'Qalyubia', cities: ['Benha', 'Shubra El Kheima', 'Qaha', 'Khanka'] },
    { name: 'Port Said', cities: ['Port Said', 'Port Fuad'] },
    { name: 'Suez', cities: ['Suez', 'Ain Sokhna'] },
    { name: 'Luxor', cities: ['Luxor', 'Esna', 'Armant'] },
    { name: 'Aswan', cities: ['Aswan', 'Kom Ombo', 'Edfu'] },
  ],
  KE: [
    { name: 'Nairobi', cities: ['Nairobi', 'Kangemi', 'Kibera', 'Kasarani'] },
    { name: 'Mombasa', cities: ['Mombasa', 'Likoni', 'Nyali', 'Bamburi'] },
    { name: 'Kisumu', cities: ['Kisumu', 'Maseno', 'Ahero', 'Muhoroni'] },
    { name: 'Nakuru', cities: ['Nakuru', 'Naivasha', 'Gilgil', 'Molo'] },
    { name: 'Eldoret', cities: ['Eldoret', 'Turbo', 'Burnt Forest', 'Ziwa'] },
    { name: 'Thika', cities: ['Thika', 'Ruiru', 'Juja', 'Gatundu'] },
    { name: 'Malindi', cities: ['Malindi', 'Watamu', 'Gede', 'Magarini'] },
    { name: 'Kitale', cities: ['Kitale', 'Kapenguria', 'Lodwar', 'Kakuma'] },
  ],
  GH: [
    { name: 'Greater Accra', cities: ['Accra', 'Tema', 'Madina', 'Adenta'] },
    { name: 'Ashanti', cities: ['Kumasi', 'Obuasi', 'Ejisu', 'Mampong'] },
    { name: 'Western', cities: ['Sekondi-Takoradi', 'Tarkwa', 'Axim', 'Half Assini'] },
    { name: 'Central', cities: ['Cape Coast', 'Elmina', 'Winneba', 'Kasoa'] },
    { name: 'Eastern', cities: ['Koforidua', 'Akosombo', 'Nkawkaw', 'Akim Oda'] },
    { name: 'Volta', cities: ['Ho', 'Hohoe', 'Keta', 'Aflao'] },
    { name: 'Northern', cities: ['Tamale', 'Yendi', 'Savelugu', 'Gushegu'] },
    { name: 'Upper East', cities: ['Bolgatanga', 'Navrongo', 'Bawku', 'Paga'] },
    { name: 'Upper West', cities: ['Wa', 'Lawra', 'Jirapa', 'Tumu'] },
    { name: 'Brong Ahafo', cities: ['Sunyani', 'Techiman', 'Berekum', 'Dormaa Ahenkro'] },
  ],
  ET: [
    { name: 'Addis Ababa', cities: ['Addis Ababa', 'Bole', 'Kirkos', 'Yeka'] },
    { name: 'Oromia', cities: ['Adama', 'Jimma', 'Bishoftu', 'Shashamane'] },
    { name: 'Amhara', cities: ['Bahir Dar', 'Gondar', 'Dessie', 'Debre Markos'] },
    { name: 'Tigray', cities: ['Mekelle', 'Axum', 'Adigrat', 'Shire'] },
    { name: 'SNNP', cities: ['Hawassa', 'Arba Minch', 'Dilla', 'Sodo'] },
    { name: 'Somali', cities: ['Jijiga', 'Gode', 'Kebri Dehar', 'Degahbur'] },
    { name: 'Afar', cities: ['Semera', 'Asaita', 'Awash', 'Dubti'] },
    { name: 'Gambela', cities: ['Gambela', 'Abobo', 'Gog', 'Jor'] },
  ],
  UG: [
    { name: 'Central', cities: ['Kampala', 'Entebbe', 'Mukono', 'Jinja'] },
    { name: 'Eastern', cities: ['Mbale', 'Soroti', 'Tororo', 'Busia'] },
    { name: 'Northern', cities: ['Gulu', 'Lira', 'Arua', 'Kitgum'] },
    { name: 'Western', cities: ['Mbarara', 'Fort Portal', 'Kasese', 'Kabale'] },
  ],
  TZ: [
    { name: 'Dar es Salaam', cities: ['Dar es Salaam', 'Kinondoni', 'Ilala', 'Temeke'] },
    { name: 'Arusha', cities: ['Arusha', 'Moshi', 'Karatu', 'Monduli'] },
    { name: 'Mwanza', cities: ['Mwanza', 'Musoma', 'Bukoba', 'Tarime'] },
    { name: 'Dodoma', cities: ['Dodoma', 'Kondoa', 'Mpwapwa', 'Chamwino'] },
    { name: 'Mbeya', cities: ['Mbeya', 'Iringa', 'Songea', 'Njombe'] },
    { name: 'Morogoro', cities: ['Morogoro', 'Ifakara', 'Kilosa', 'Mvomero'] },
    { name: 'Tanga', cities: ['Tanga', 'Pangani', 'Lushoto', 'Korogwe'] },
    { name: 'Zanzibar', cities: ['Stone Town', 'Chake Chake', 'Wete', 'Mkoani'] },
  ],
  DZ: [
    { name: 'Algiers', cities: ['Algiers', 'Bab El Oued', 'Hussein Dey', 'Kouba'] },
    { name: 'Oran', cities: ['Oran', 'Es Senia', 'Bir El Djir', 'Sidi Bel Abbès'] },
    { name: 'Constantine', cities: ['Constantine', 'Hamma Bouziane', 'Didouche Mourad'] },
    { name: 'Annaba', cities: ['Annaba', 'El Hadjar', 'Sidi Amar', 'Berrahal'] },
    { name: 'Blida', cities: ['Blida', 'Boufarik', 'Larbaa', 'Soumaa'] },
    { name: 'Batna', cities: ['Batna', 'Barika', 'Ain Touta', 'Arris'] },
    { name: 'Djelfa', cities: ['Djelfa', 'Ain Oussera', 'Hassi Bahbah', 'Birine'] },
    { name: 'Sétif', cities: ['Sétif', 'El Eulma', 'Ain Arnat', 'Bougaa'] },
  ],
  MA: [
    { name: 'Casablanca-Settat', cities: ['Casablanca', 'Settat', 'El Jadida', 'Mohammedia'] },
    { name: 'Rabat-Salé-Kénitra', cities: ['Rabat', 'Salé', 'Kénitra', 'Témara'] },
    { name: 'Fès-Meknès', cities: ['Fès', 'Meknès', 'Taza', 'Sefrou'] },
    { name: 'Marrakech-Safi', cities: ['Marrakech', 'Safi', 'Essaouira', 'El Kelaa des Sraghna'] },
    { name: 'Oriental', cities: ['Oujda', 'Nador', 'Berkane', 'Taourirt'] },
    { name: 'Tangier-Tétouan-Al Hoceïma', cities: ['Tangier', 'Tétouan', 'Al Hoceïma', 'Larache'] },
    { name: 'Souss-Massa', cities: ['Agadir', 'Inezgane', 'Taroudant', 'Tiznit'] },
    { name: 'Drâa-Tafilalet', cities: ['Errachidia', 'Ouarzazate', 'Zagora', 'Midelt'] },
  ],
  AO: [
    { name: 'Luanda', cities: ['Luanda', 'Viana', 'Cacuaco', 'Belas'] },
    { name: 'Huíla', cities: ['Lubango', 'Matala', 'Chibia', 'Humpata'] },
    { name: 'Benguela', cities: ['Benguela', 'Lobito', 'Catumbela', 'Ganda'] },
    { name: 'Huambo', cities: ['Huambo', 'Caála', 'Bailundo', 'Ecunha'] },
    { name: 'Uíge', cities: ['Uíge', 'Negage', 'Songo', 'Mucaba'] },
    { name: 'Malanje', cities: ['Malanje', 'Cacuso', 'Calandula', 'Cambundi-Catembo'] },
    { name: 'Lunda Norte', cities: ['Dundo', 'Lucapa', 'Capenda-Camulemba', 'Cuango'] },
    { name: 'Cabinda', cities: ['Cabinda', 'Cacongo', 'Buco-Zau', 'Belize'] },
  ],
  CM: [
    { name: 'Centre', cities: ['Yaoundé', 'Mbalmayo', 'Akonolinga', 'Bafia'] },
    { name: 'Littoral', cities: ['Douala', 'Nkongsamba', 'Edéa', 'Loum'] },
    { name: 'West', cities: ['Bafoussam', 'Dschang', 'Mbouda', 'Bandjoun'] },
    { name: 'Northwest', cities: ['Bamenda', 'Kumbo', 'Wum', 'Ndop'] },
    { name: 'Southwest', cities: ['Buea', 'Limbe', 'Kumba', 'Mamfe'] },
    { name: 'North', cities: ['Garoua', 'Maroua', 'Ngaoundéré', 'Guider'] },
    { name: 'Far North', cities: ['Maroua', 'Kousseri', 'Mokolo', 'Yagoua'] },
    { name: 'East', cities: ['Bertoua', 'Batouri', 'Abong-Mbang', 'Yokadouma'] },
    { name: 'South', cities: ['Ebolowa', 'Kribi', 'Sangmélima', 'Ambam'] },
    { name: 'Adamawa', cities: ['Ngaoundéré', 'Meiganga', 'Tibati', 'Tignère'] },
  ],
  CI: [
    { name: 'Abidjan', cities: ['Abidjan', 'Yopougon', 'Abobo', 'Cocody'] },
    { name: 'Yamoussoukro', cities: ['Yamoussoukro', 'Attiégouakro', 'Kossou'] },
    { name: 'Bouaké', cities: ['Bouaké', 'Katiola', 'Béoumi', 'Sakassou'] },
    { name: 'Daloa', cities: ['Daloa', 'Issia', 'Vavoua', 'Zoukougbeu'] },
    { name: 'San-Pédro', cities: ['San-Pédro', 'Sassandra', 'Soubré', 'Tabou'] },
    { name: 'Korhogo', cities: ['Korhogo', 'Boundiali', 'Ferkessédougou', 'Sinématiali'] },
    { name: 'Man', cities: ['Man', 'Danané', 'Biankouma', 'Sipilou'] },
    { name: 'Divo', cities: ['Divo', 'Lakota', 'Guitry', 'Fresco'] },
  ],
  SN: [
    { name: 'Dakar', cities: ['Dakar', 'Pikine', 'Guédiawaye', 'Rufisque'] },
    { name: 'Thiès', cities: ['Thiès', 'Mbour', 'Tivaouane', 'Joal-Fadiouth'] },
    { name: 'Saint-Louis', cities: ['Saint-Louis', 'Dagana', 'Podor', 'Richard-Toll'] },
    { name: 'Diourbel', cities: ['Diourbel', 'Touba', 'Mbacké', 'Bambey'] },
    { name: 'Kaolack', cities: ['Kaolack', 'Kaffrine', 'Nioro du Rip', 'Foundiougne'] },
    { name: 'Tambacounda', cities: ['Tambacounda', 'Bakel', 'Goudiry', 'Koumpentoum'] },
    { name: 'Ziguinchor', cities: ['Ziguinchor', 'Oussouye', 'Bignona', 'Kolda'] },
    { name: 'Fatick', cities: ['Fatick', 'Gossas', 'Foundiougne', 'Sokone'] },
  ],
  // Add more countries as needed
};

export const getCountryByCode = (code: string): Country | undefined => {
  return COUNTRIES.find(country => country.cca2 === code);
};

export const getStatesByCountry = (countryCode: string): State[] => {
  return STATES_BY_COUNTRY[countryCode] || [];
};

export const getCitiesByState = (countryCode: string, stateName: string): string[] => {
  const states = STATES_BY_COUNTRY[countryCode] || [];
  const state = states.find(s => s.name === stateName);
  return state?.cities || [];
};
